# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  elevation: 250
  unit_system: metric
  time_zone: Europe/Minsk
  external_url: !secret duckdns_url
  internal_url: http://192.168.1.31:8123
  customize: !include customize.yaml
  
zone:
  - name: Home
    latitude: !secret latitude_coord
    longitude: !secret longitude_coord
    radius: 10
    icon: mdi:home

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list includes/sensor
camera: !include includes/cameras.yaml



