default_config:

homeassistant:
  name: HomeRPI4
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 250
  unit_system: metric
  time_zone: Europe/Minsk
  external_url: !secret duckdns_external_url
  internal_url: !secret duckdns_internal_url
  customize: !include customize.yaml
  media_dirs:
    motion: /config/www/cam_captures

zone: !include includes/zones.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include_dir_merge_named includes/scripts
scene: !include scenes.yaml
sensor: !include_dir_merge_list includes/sensor
camera: !include includes/cameras.yaml
utility_meter: !include includes/utility_meter.yaml

logger:
  default: info
#   logs:
#     homeassistant.components.zha: debug
#     homeassistant.setup: debug
#     homeassistant.config_entries: debug
#     zigpy_cc.api: debug
#     zigpy.application: debug

lovelace:
  mode: yaml
  resources:
    - url: /local/zha-network-visualization-card/zha-network-visualization-card.js
      type: module

# Xiaomi Philips Ceiling LED
light:
  - platform: xiaomi_miio
    name: Xiaomi Philips Ceiling LED
    host: 192.168.1.10
    token: !secret xiaomi_philips_ceiling_led_token
    model: philips.light.ceiling

# Xiaomi zimi powerstrip
switch:
  - platform: xiaomi_miio
    host: 192.168.1.18
    token: !secret xiaomi_zimi_powerstrip_token
    model: zimi.powerstrip.v2
  
# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id_alex

notify: 
  - platform: telegram
    name: Telegram
    chat_id: !secret telegram_chat_id_alex
    
#  - platform: webostv
#    name: LG TV
#    host: 192.168.1.11
#    filename: webostv.conf


# Need for TVs
wake_on_lan:

# LG TV
webostv:
  host: 192.168.1.11
  name: LG TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: 7C:1C:4E:4B:83:86 
      broadcast_address: 192.168.1.255
      broadcast_port: 9

# Samsung TV
# samsungtv:
#   host: 192.168.1.7
#   name: Samsung TV
#   turn_on_action:
#     service: wake_on_lan.send_magic_packet
#     data:
#       #mac: 04:20:9A:28:11:FB 
#       mac: BC:14:85:E8:CE:2B
#       broadcast_address: 192.168.1.255
#       broadcast_port: 9

# Sonoff
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  
# Speedtest  
speedtestdotnet:
  scan_interval: '02:00:00'
  monitored_conditions:
    - ping
    - download
    - upload

# ZHA network map  
zha_map:





